// Server-only helpers for the AI presentation generator.
import { generateTextWithFallback } from "./ai-provider.server";
import { geminiGenerateImage, fallbackGenerateImage } from "./gemini";

export function outlinePrompt(topic: string, grade: string, language: string, count: number) {
  return `Create the slide OUTLINE for an educational presentation.

Topic: "${topic}"
Audience / level: ${grade}
Language: ${language}
Number of slides: exactly ${count}

Rules:
- Slide 1 is the title slide, the last slide is a closing "Summary / Thank You" slide.
- Middle slides must follow a logical teaching order (introduction, definition, history/background, key facts, causes, processes, effects, examples, importance, advantages/limitations) chosen to fit THIS topic.
- Titles are short (2-6 words), specific to the topic, never generic filler.
- Depth and vocabulary must match ${grade} exactly.

Return JSON only:
{"title":string,"subject":string,"slides":[{"title":string,"purpose":string}]}`;
}

export function slidePrompt(args: {
  topic: string;
  grade: string;
  language: string;
  deckTitle: string;
  subject: string;
  slideTitle: string;
  purpose: string;
  index: number;
  total: number;
  previousTitles: string[];
}) {
  return `You are writing slide ${args.index + 1} of ${args.total} for the educational presentation "${args.deckTitle}" (subject: ${args.subject}, level: ${args.grade}, language: ${args.language}).

Overall topic: "${args.topic}"
This slide's title: "${args.slideTitle}"
This slide's purpose: ${args.purpose}
Slides already written: ${args.previousTitles.join(" | ") || "none"} — never repeat their content.

Slide writing rules:
- 3 to 5 bullets, each a complete, factual, exam-useful statement of 6-16 words. No filler, no placeholders.
- Optional short subtitle (max 8 words).
- "speakerNotes": 3-4 sentences of extra depth the teacher says aloud.
- Content accuracy and difficulty must match ${args.grade}.

IMAGE PROMPT rules — this is critical:
- Write "imagePrompt": a rich, highly specific prompt for an AI image model describing a real scene/object/illustration for THIS slide only.
- It must depict the actual subject matter (e.g. a Victorian textile factory with steam engines and smoke; a convex lens bending light rays on an optical bench; a population pyramid chart of India).
- Choose the visual style automatically from the subject: history -> photorealistic historical reconstruction; biology -> detailed scientific illustration; geography -> map or landscape; chemistry -> laboratory scene; physics -> clear experimental setup; computer science -> technology visual; mathematics -> clean graph/geometry visual.
- End the prompt with: "ultra detailed, high resolution, cinematic lighting, educational, no text, no watermark".
- Never reuse a previous slide's imagery. Never describe generic stock scenes, offices, houses, or people posing.

Return JSON only:
{"title":string,"subtitle":string,"bullets":string[],"speakerNotes":string,"imagePrompt":string}`;
}

export function parseJson<T>(text: string): T {
  const cleaned = text.trim().replace(/^```(?:json)?/i, "").replace(/```$/, "");
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  const slice = start >= 0 && end > start ? cleaned.slice(start, end + 1) : cleaned;
  return JSON.parse(slice) as T;
}

export async function askJson<T>(prompt: string, maxOutputTokens = 4096): Promise<T> {
  const res = await generateTextWithFallback([{ role: "user", parts: [{ text: prompt }] }], {
    system:
      "You are Nexora AI, an expert curriculum designer and presentation writer. You always return strictly valid JSON, never markdown fences, never commentary.",
    json: true,
    temperature: 0.75,
    maxOutputTokens,
  });
  return parseJson<T>(res.text);
}

/**
 * Slide imagery is ALWAYS generated by an AI image model — never stock search.
 * Order: Gemini image models -> keyless AI generator (Flux/Turbo diffusion).
 */
export async function generateAiImage(
  prompt: string,
  attempt: number,
): Promise<{ dataUrl: string; model: string } | { error: string }> {
  const key = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  if (key) {
    const g = await geminiGenerateImage(key, prompt, attempt);
    if (g.ok) return { dataUrl: g.dataUrl, model: g.model };
  }
  const f = await fallbackGenerateImage(prompt, attempt);
  if (f.ok) return { dataUrl: f.dataUrl, model: f.model };
  return { error: f.error };
}